# Generated by Django 4.2.3 on 2023-10-04 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='nombre')),
                ('photo_portada', models.ImageField(null=True, upload_to='catalogo', verbose_name='portada')),
                ('description', models.TextField(max_length=100, null=True, verbose_name='descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha actualizacion')),
            ],
            options={
                'verbose_name': 'Catalogo',
                'verbose_name_plural': 'Catalogos',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('type_categorie', models.CharField(max_length=15, verbose_name='tipo_categoria')),
                ('description', models.TextField(verbose_name='descripcion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha actualizacion')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha actualizacion')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileBussines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('bio', models.TextField(max_length=50, null=True)),
                ('photo_portada', models.ImageField(null=True, upload_to='perfil_bussines', verbose_name='portada')),
                ('photo_profile', models.ImageField(null=True, upload_to='perfil_bussines', verbose_name='perfil')),
                ('description', models.TextField(max_length=500, verbose_name='descripcion')),
                ('contact', models.CharField(max_length=50, verbose_name='contacto')),
                ('email', models.EmailField(max_length=254, verbose_name='correo')),
                ('facebook', models.CharField(max_length=300, null=True)),
                ('instagram', models.CharField(max_length=300, null=True)),
                ('whatsapp', models.CharField(max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha actualizacion')),
                ('category', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='company.category', verbose_name='categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Perfil-Empresa',
                'verbose_name_plural': 'Perfiles-Empresas',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_service', models.CharField(max_length=10, unique=True, verbose_name='id_producto')),
                ('name_service', models.CharField(max_length=40, verbose_name='Nombre')),
                ('description', models.TextField(default='Descripcion del producto', max_length=400, verbose_name='descripcion')),
                ('status', models.CharField(default='Activo', max_length=20, verbose_name='estado')),
                ('price', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='precio')),
                ('photo_service1', models.ImageField(upload_to='productos', verbose_name='foto_producto1')),
                ('photo_service2', models.ImageField(null=True, upload_to='productos', verbose_name='foto_producto2')),
                ('photo_service3', models.ImageField(null=True, upload_to='productos', verbose_name='foto_producto3')),
                ('photo_service4', models.ImageField(null=True, upload_to='productos', verbose_name='foto_producto4')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.catalogos', verbose_name='catalogo')),
                ('category', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='company.category', verbose_name='Categoria')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.profilebussines', verbose_name='Perfil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_product', models.CharField(max_length=10, unique=True, verbose_name='id_producto')),
                ('name_product', models.CharField(max_length=40, verbose_name='Nombre')),
                ('quantities', models.CharField(max_length=4, null=True, verbose_name='Cantidades')),
                ('description', models.TextField(default='Descripcion del producto', max_length=400, verbose_name='descripcion')),
                ('status', models.CharField(default='Activo', max_length=20, verbose_name='estado')),
                ('price', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='precio')),
                ('photo_product1', models.ImageField(upload_to='productos', verbose_name='foto_producto1')),
                ('photo_product2', models.ImageField(null=True, upload_to='productos', verbose_name='foto_producto2')),
                ('photo_product3', models.ImageField(null=True, upload_to='productos', verbose_name='foto_producto3')),
                ('photo_product4', models.ImageField(null=True, upload_to='productos', verbose_name='foto_producto4')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.catalogos', verbose_name='catalogo')),
                ('category', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='company.category', verbose_name='Categoria')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.profilebussines', verbose_name='Perfil')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.AddField(
            model_name='catalogos',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.category', verbose_name='categoria'),
        ),
        migrations.AddField(
            model_name='catalogos',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.profilebussines', verbose_name='perfil'),
        ),
        migrations.AddField(
            model_name='catalogos',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateTimeField(verbose_name='Cumpleaños')),
                ('country', models.CharField(max_length=50, verbose_name='Pais')),
                ('indicative', models.CharField(max_length=3, verbose_name='Indicativo')),
                ('contact', models.CharField(max_length=30, null=True, verbose_name='Contacto')),
                ('gender', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otros', 'Otros')], max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha actualizacion')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
