# Generated by Django 4.2.3 on 2023-08-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebussines',
            name='facebook',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profilebussines',
            name='instagram',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profilebussines',
            name='whatsapp',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
