# Generated by Django 4.2.3 on 2023-08-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_profilebussines_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilebussines',
            name='bio',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profilebussines',
            name='photo_portada',
            field=models.ImageField(null=True, upload_to='perfil_bussines', verbose_name='portada'),
        ),
        migrations.AlterField(
            model_name='profilebussines',
            name='photo_profile',
            field=models.ImageField(null=True, upload_to='perfil_bussines', verbose_name='perfil'),
        ),
    ]
