# Generated by Django 4.2.3 on 2023-10-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_account_bio_account_city_account_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='photo_profile',
            field=models.ImageField(null=True, upload_to='perfil_bussines', verbose_name='perfil'),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otros', 'Otros')], max_length=6, null=True, verbose_name='Genero'),
        ),
    ]
