# Generated by Django 4.2.3 on 2023-10-11 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_account_photo_profile_alter_account_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogos',
            name='type_catalog',
            field=models.CharField(choices=[('Servicios', 'Productos')], default=1, max_length=10, verbose_name='Tipo catalogo'),
            preserve_default=False,
        ),
    ]
