# Generated by Django 4.2.3 on 2023-08-31 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_profilebussines_bio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogos',
            name='description',
            field=models.TextField(max_length=100, null=True, verbose_name='descripcion'),
        ),
        migrations.AddField(
            model_name='catalogos',
            name='photo_portada',
            field=models.ImageField(null=True, upload_to='catalogo', verbose_name='portada'),
        ),
    ]
