# Generated by Django 4.2.3 on 2023-08-31 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0004_catalogos_description_catalogos_photo_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogos',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.profilebussines', verbose_name='perfil'),
        ),
        migrations.AddField(
            model_name='catalogos',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
