# Generated by Django 4.2.3 on 2023-10-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_alter_services_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='services',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(default='Descripcion del servicio', max_length=400, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='services',
            name='id_service',
            field=models.CharField(max_length=10, unique=True, verbose_name='id_servicio'),
        ),
        migrations.AlterField(
            model_name='services',
            name='photo_service1',
            field=models.ImageField(upload_to='servicios', verbose_name='foto_servicio1'),
        ),
        migrations.AlterField(
            model_name='services',
            name='photo_service2',
            field=models.ImageField(null=True, upload_to='servicios', verbose_name='foto_servicio2'),
        ),
        migrations.AlterField(
            model_name='services',
            name='photo_service3',
            field=models.ImageField(null=True, upload_to='servicios', verbose_name='foto_servicio3'),
        ),
        migrations.AlterField(
            model_name='services',
            name='photo_service4',
            field=models.ImageField(null=True, upload_to='servicios', verbose_name='foto_servicio4'),
        ),
    ]
