# Generated by Django 4.2.3 on 2023-10-27 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_products_price_promo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='valoration',
            field=models.CharField(default='3.5', max_length=3, verbose_name='Valoracion'),
        ),
        migrations.AlterField(
            model_name='services',
            name='valoration',
            field=models.CharField(default='3.5', max_length=3, verbose_name='Valoracion'),
        ),
    ]
