# Generated by Django 4.2.3 on 2023-11-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_products_valoration_alter_services_valoration'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='color',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
