# Generated by Django 4.2.3 on 2023-11-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_alter_products_name_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.TextField(default='Descripcion del producto', max_length=1000, verbose_name='descripcion'),
        ),
    ]
