# Generated by Django 4.2.3 on 2023-11-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_alter_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogos',
            name='description',
            field=models.TextField(max_length=2000, null=True, verbose_name='descripcion'),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.TextField(default='Descripcion del servicio', max_length=1000, verbose_name='descripcion'),
        ),
    ]
