# Generated by Django 4.2.3 on 2023-11-23 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_alter_catalogos_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='catalog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='company.catalogos', verbose_name='catalogo'),
        ),
    ]
